"""QSS template inventory for the Photo Editor UI.

This package is the central place for palette-aware Qt stylesheet templates used
throughout the application. Templates are loaded through
``photo_editor.ui.styles.load_qss_template()`` and usually rendered with
``render_qss()`` using ``[[token]]`` placeholders.

The list below explains what each QSS file is responsible for so the folder can
be used as the quick visual-edit surface for the app.

App shell
---------
- ``base.qss``: global application widget defaults generated by the theme
  manager.
- ``menu_bar.qss``: top menu bar styling.
- ``toolbar.qss``: main left tool toolbar styling.
- ``tool_flyout_container.qss``: popup container for grouped tool flyouts.
- ``tool_flyout_button.qss``: individual buttons inside tool flyout popups.
- ``props_toolbar.qss``: compact toolbar above the properties area.
- ``file_tabs.qss``: document tab strip styling.
- ``file_close_button.qss``: close button shown in file tabs.

Status bar
----------
- ``status_bar.qss``: status bar surface and text colors.
- ``status_bar_pill.qss``: pill-style status badges.
- ``status_bar_checkbox.qss``: checkbox styling inside the status bar.
- ``status_bar_dot.qss``: small indicator dot styling.

Color widgets
-------------
- ``color_popup_container.qss``: popup shell for color dropdowns.
- ``color_popup_tabs.qss``: tabs inside the color popup.
- ``control_line_edit.qss``: shared single-line editor template for small
  controls such as hex inputs.

Generic shared controls
-----------------------
- ``icon_button.qss``: shared icon/flat button template with hover, pressed,
  and checked states.
- ``panel_surface.qss``: shared panel background and row-hover template.

Layers panel
------------
- ``layers_panel_root.qss``: overall layers panel surface.
- ``layers_panel_header.qss``: layers panel top control row.
- ``layers_panel_opacity_label.qss``: opacity label in the layers header.
- ``layers_panel_spin.qss``: layers panel spin boxes.
- ``layers_panel_combo.qss``: layers panel combo boxes.
- ``layers_panel_slider.qss``: layers panel opacity slider.
- ``layers_panel_toolbar.qss``: layers action toolbar.
- ``layers_panel_menu_button.qss``: adjustment/filter menu buttons.
- ``layers_panel_menu.qss``: adjustment/filter popup menus.
- ``layers_panel_separator_line.qss``: separator line used between groups.
- ``layers_panel_separator_widget.qss``: separator widget container styling.
- ``layer_list.qss``: list widget hosting layer rows.
- ``layer_item_root.qss``: base styling for a single layer row.
- ``layer_item_arrow.qss``: expand/collapse arrow button for groups.
- ``layer_item_thumb.qss``: thumbnail frame styling.
- ``layer_item_name.qss``: layer name label styling.
- ``layer_item_transparent.qss``: transparent utility styling for overlay
  labels/icons.
- ``layer_item_visibility_button.qss``: visibility toggle button styling.

Properties panel
----------------
- ``properties_panel.qss``: root surface for the properties panel.
- ``properties_dropdown.qss``: popup/dropdown widgets in properties controls.
- ``properties_label.qss``: standard property label appearance.
- ``properties_separator.qss``: separators between property groups.
- ``properties_toggle.qss``: toggle buttons in properties controls.
- ``properties_align_button.qss``: alignment/action buttons used by some
  property bars.
- ``properties_spin.qss``: shared spin box template for property editors.
- ``properties_combo.qss``: shared combo box template for property editors.
- ``properties_flat_button.qss``: flat action buttons inside properties bars.
- ``properties_expand_button.qss``: expand/collapse affordance for grouped
  property rows.

Dialogs and specialty panels
----------------------------
- ``shortcuts_dialog.qss``: keyboard shortcuts dialog shell and list styling.
- ``brushes_panel.qss``: docked brushes browser styling.

The module also exposes ``QSS_FILE_DESCRIPTIONS`` for quick programmatic lookup
when auditing or documenting UI styles.
"""

from __future__ import annotations


QSS_FILE_DESCRIPTIONS: dict[str, str] = {
    "base.qss": "Global application widget defaults generated by the theme manager.",
    "brushes_panel.qss": "Docked brushes browser styling.",
    "color_popup_container.qss": "Popup shell for color dropdown widgets.",
    "color_popup_tabs.qss": "Tabs inside the color popup.",
    "control_line_edit.qss": "Shared single-line editor template for compact inputs.",
    "file_close_button.qss": "Close button shown in file tabs.",
    "file_tabs.qss": "Document tab strip styling.",
    "icon_button.qss": "Shared icon/flat button template with hover and checked states.",
    "layers_panel_combo.qss": "Combo boxes in the layers panel header.",
    "layers_panel_header.qss": "Top control row of the layers panel.",
    "layers_panel_menu.qss": "Adjustment/filter popup menus for the layers panel.",
    "layers_panel_menu_button.qss": "Adjustment/filter menu buttons in the layers panel.",
    "layers_panel_opacity_label.qss": "Opacity label styling in the layers panel.",
    "layers_panel_root.qss": "Overall layers panel surface.",
    "layers_panel_separator_line.qss": "Separator line used between layer groups.",
    "layers_panel_separator_widget.qss": "Separator widget container styling for the layers panel.",
    "layers_panel_slider.qss": "Opacity slider in the layers panel.",
    "layers_panel_spin.qss": "Spin boxes in the layers panel.",
    "layers_panel_toolbar.qss": "Action toolbar inside the layers panel.",
    "layer_item_arrow.qss": "Expand/collapse arrow button for grouped layer rows.",
    "layer_item_name.qss": "Layer name label styling.",
    "layer_item_root.qss": "Base styling for a single layer row.",
    "layer_item_thumb.qss": "Thumbnail frame styling in layer rows.",
    "layer_item_transparent.qss": "Transparent utility styling for overlay labels and icons.",
    "layer_item_visibility_button.qss": "Visibility toggle button in layer rows.",
    "layer_list.qss": "List widget hosting layer rows.",
    "menu_bar.qss": "Top menu bar styling.",
    "panel_surface.qss": "Shared panel background and row-hover template.",
    "properties_align_button.qss": "Alignment/action buttons used by property bars.",
    "properties_combo.qss": "Shared combo box template for property editors.",
    "properties_dropdown.qss": "Dropdown and popup widgets in properties controls.",
    "properties_expand_button.qss": "Expand/collapse affordance for grouped property rows.",
    "properties_flat_button.qss": "Flat action buttons inside properties bars.",
    "properties_label.qss": "Standard property label appearance.",
    "properties_panel.qss": "Root surface for the properties panel.",
    "properties_separator.qss": "Separators between property groups.",
    "properties_spin.qss": "Shared spin box template for property editors.",
    "properties_toggle.qss": "Toggle buttons in properties controls.",
    "props_toolbar.qss": "Compact toolbar above the properties area.",
    "shortcuts_dialog.qss": "Keyboard shortcuts dialog shell and tree/list styling.",
    "status_bar.qss": "Status bar surface and text colors.",
    "status_bar_checkbox.qss": "Checkbox styling inside the status bar.",
    "status_bar_dot.qss": "Small indicator dot styling.",
    "status_bar_pill.qss": "Pill-style status badges.",
    "toolbar.qss": "Main tool toolbar styling.",
    "tool_flyout_button.qss": "Buttons inside grouped tool flyout popups.",
    "tool_flyout_container.qss": "Popup container for grouped tool flyouts.",
}


def describe_qss_file(name: str) -> str:
    """Return the short purpose string for a QSS template file."""
    return QSS_FILE_DESCRIPTIONS[name]


__all__ = ["QSS_FILE_DESCRIPTIONS", "describe_qss_file"]